Installing Packages

In [1]:
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format

Importing the Data

In [2]:
df_orders = pd.read_csv('../data/raw/orders.csv')

print(df_orders.columns)
print(df_orders.shape)
df_orders.head()

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')
(3421083, 7)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00

In [3]:
# Reading data
df_orders_products_train = pd.read_csv('../data/raw/order_products_train.csv')
print(df_orders_products_train.columns)
print(df_orders_products_train.shape)
df_orders_products_train.head()

Index(['order_id', 'product_id', 'add_to_cart_order', 'reordered'], dtype='str')
(1384617, 4)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [4]:
df_products = pd.read_csv("../data/raw/products.csv")
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.80
1,2,All-Seasons Salt,104,13,9.30
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50
4,5,Green Chile Anytime Sauce,5,13,4.30

In [5]:
df_departments = pd.read_csv('../data/processed/departments_t.csv')
print(df_departments.columns)
print(df_departments.shape)
df_departments.head()

Index(['Excel', 'SQL'], dtype='str')
(21, 2)

   Excel      SQL
0      1   frozen
1      2    other
2      3   bakery
3      4  produce
4      5  alcohol

In [6]:
df_aisles = pd.read_csv('../data/raw/aisles.csv')
print(df_aisles.columns)
print(df_aisles.shape)
df_aisles.head()

Index(['aisle_id', 'aisle'], dtype='str')
(134, 2)

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

Working with 'Orders'

In [7]:
pd.options.display.float_format = '{:,.2f}'.format
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,"3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,214,874.00"
mean,"1,710,542.00","102,978.21",17.15,2.78,13.45,11.11
std,"987,581.74","59,533.72",17.73,2.05,4.23,9.21
min,1.00,1.00,1.00,0.00,0.00,0.00
25%,"855,271.50","51,394.00",5.00,1.00,10.00,4.00
50%,"1,710,542.00","102,689.00",11.00,3.00,13.00,7.00
75%,"2,565,812.50","154,385.00",23.00,5.00,16.00,15.00
max,"3,421,083.00","206,209.00",100.00,6.00,23.00,30.00

In [8]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00

In [9]:
df_orders.isna().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

Q1: How many unique orders exist?

In [10]:
df_orders["order_id"].nunique()

3421083

In [11]:
df_orders.shape

(3421083, 7)

In [12]:
## Consistency Check: Order ID
if df_orders['order_id'].nunique() == df_orders.shape[0]:
    print('Happy')
else:
    print('Sad')

Happy

Q2: How many distinct customers are represented in the dataset?

In [13]:
df_orders["user_id"].nunique()

206209

In [14]:
df_orders["order_id"].nunique()/df_orders["user_id"].nunique()

16.590367054784224

Q3: Exploring the eval_set distribution

In [15]:
df_orders["eval_set"].value_counts(dropna=False)

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [16]:
df_dow = df_orders["order_dow"].value_counts().reset_index()
df_dow

   order_dow   count
0          0  600905
1          1  587478
2          2  467260
3          5  453368
4          6  448761
5          3  436972
6          4  426339

In [17]:
df_dow.sort_values('order_dow')

   order_dow   count
0          0  600905
1          1  587478
2          2  467260
5          3  436972
6          4  426339
3          5  453368
4          6  448761

In [18]:
df_dow.to_csv('../data/processed/dow.csv', index=False)

In [19]:
df_ohod = df_orders['order_hour_of_day'].value_counts().reset_index().sort_values('order_hour_of_day')
df_ohod.head()

    order_hour_of_day  count
18                  0  22758
19                  1  12398
21                  2   7539
23                  3   5474
22                  4   5527

In [20]:
#import sys
#print(sys.executable)

In [21]:
#!pip show openpyxl

In [22]:
#!pip install openpyxl

In [23]:
df_ohod.to_excel('../data/processed/ohod.xlsx', index = False)

In [24]:
df_orders.loc[df_orders["order_number"] == 1, "days_since_prior_order"].isna().all()

np.True_

In [31]:
needed_columns = ['days_since_prior_order', 'order_number', 'user_id']

In [ ]:
#df_orders[['days_since_prior_order', 'order_number']].head()
#df_first_orders = df_orders[needed_columns][df_orders['order_number'] == 1]
#print(df_first_orders.head())
#df_first_orders.reset_index(inplace=True)
#df_first_orders.head()

    days_since_prior_order  order_number  user_id
0                      NaN             1        1
11                     NaN             1        2
26                     NaN             1        3
39                     NaN             1        4
45                     NaN             1        5

   index  days_since_prior_order  order_number  user_id
0      0                     NaN             1        1
1     11                     NaN             1        2
2     26                     NaN             1        3
3     39                     NaN             1        4
4     45                     NaN             1        5

In [44]:
df_first_orders = df_orders[needed_columns][df_orders['order_number'] == 1].reset_index()
#df_first_orders.drop(columns='index', inplace=True)
df_first_orders = df_first_orders.drop(columns='index')

In [33]:
df_orders.iloc[26]

order_id                  1374495
user_id                         3
eval_set                    prior
order_number                    1
order_dow                       1
order_hour_of_day              14
days_since_prior_order        NaN
Name: 26, dtype: object

In [46]:
if df_orders["order_id"].is_unique:
    print('Happy')

Happy

In [47]:
df_orders["order_dow"].between(0, 6).all()

np.True_

In [48]:
df_orders["order_hour_of_day"].between(0, 23).all()

np.True_

In [49]:
df_orders_train = df_orders[df_orders["eval_set"] == "train"]
df_orders_train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.00
25,1492625,2,train,15,1,11,30.00
49,2196797,5,train,5,0,11,6.00
74,525192,7,train,21,2,11,6.00
78,880375,8,train,4,1,14,10.00

In [50]:
df_orders_train.shape

(131209, 7)

In [ ]:
# Since the further analysis is going to be done based on the subset where eval_set == 'Train'
#del df_orders