Installings

In [2]:
conda install plotly

3 channel Terms of Service accepted
Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: c:\Users\Ani\miniconda3\envs\aca

  added / updated specs:
    - plotly


The following NEW packages will be INSTALLED:

  narwhals           pkgs/main/win-64::narwhals-2.7.0-py313haa95532_0
  plotly             pkgs/main/win-64::plotly-6.6.0-py313h4442805_0



Downloading and Extracting Packages: ...working... done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

==> WARNING: A newer version of conda exists. <==
    current version: 26.1.1
    latest version: 26.3.2

Please update conda by running

    $ conda update -n base -c defaults conda

In [20]:
conda install nbformat

3 channel Terms of Service accepted
Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: c:\Users\Ani\miniconda3\envs\aca

  added / updated specs:
    - nbformat


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    attrs-26.1.0               |  py313h35db113_0         177 KB
    ------------------------------------------------------------
                                           Total:         177 KB

The following NEW packages will be INSTALLED:

  attrs              pkgs/main/win-64::attrs-26.1.0-py313h35db113_0
  jsonschema         pkgs/main/win-64::jsonschema-4.25.1-py313haa95532_0
  jsonschema-specif~ pkgs/main/win-64::jsonschema-specifications-2025.9.1-py313haa95532_0
  nbformat           pkgs/main/win-64::nbformat-5.10.4-py313haa95532_0
  python-fastjsonsc~ pkgs/main/win-64::python-fastjsonschema-2.21.2-py313haa95532_0
  referencing        pkgs/main/win-64::referencing-0.37.0-py313haa95532_0
  rpds-py            pkgs/main/win-64::rpds-py-0.28.0-py313h114bc41_0



Downloading and Extracting Packages: ...working...
attrs-26.1.0         | 177 KB    |            |   0%
attrs-26.1.0         | 177 KB    | 9          |   9%
attrs-26.1.0         | 177 KB    | ########## | 100%
attrs-26.1.0         | 177 KB    | ########## | 100%
attrs-26.1.0         | 177 KB    | ########## | 100%

 done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

==> WARNING: A newer version of conda exists. <==
    current version: 26.1.1
    latest version: 26.3.2

Please update conda by running

    $ conda update -n base -c defaults conda

In [1]:
#import sys
#print(sys.executable)

Dummy Dataset for Plotly Examples

In [20]:
px.defaults.template = "plotly_white"

In [2]:
import pandas as pd
import numpy as np
import plotly.express as px

np.random.seed(42)
px.defaults.template = "plotly_white"

months = pd.date_range("2024-01-01", periods=6, freq="MS")
regions = ["North", "South", "East"]
products = ["A", "B"]

rows = []

for month in months:
    for region in regions:
        for product in products:
            sales = np.random.randint(80, 220)
            customers = np.random.randint(20, 90)
            units = np.random.randint(10, 70)
            
            rows.append([month, region, product, sales, customers, units])

df_plotly = pd.DataFrame(
    rows,
    columns=["month", "region", "product", "sales", "customers", "units"]
)

df_plotly["month_name"] = df_plotly["month"].dt.strftime("%b")
df_plotly.head()

       month region product  sales  customers  units month_name
0 2024-01-01  North       A    182         71     38        Jan
1 2024-01-01  North       B     94         80     30        Jan
2 2024-01-01  South       A    182         43     12        Jan
3 2024-01-01  South       B    132         21     33        Jan
4 2024-01-01   East       A    117         21     69        Jan

In [4]:
monthly_sales = df_plotly.groupby("month", as_index=False)[['customers', 'units', 'sales']].sum()
monthly_sales

       month  customers  units  sales
0 2024-01-01        288    203    807
1 2024-02-01        347    289    810
2 2024-03-01        380    151    831
3 2024-04-01        344    202    855
4 2024-05-01        281    207    934
5 2024-06-01        252    262    796

In [7]:
fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    #markers=True,
    title="Monthly Total Sales"
)

fig.update_layout(
    
    xaxis_title="Month",
    yaxis_title="Sales"
)

fig.show()

In [9]:
monthly_sales_pro = df_plotly.groupby(["month", "product"], as_index=False)[['customers', 'units', 'sales']].sum()
monthly_sales_pro

        month product  customers  units  sales
0  2024-01-01       A        135    119    481
1  2024-01-01       B        153     84    326
2  2024-02-01       A        176    151    405
3  2024-02-01       B        171    138    405
4  2024-03-01       A        184     69    504
5  2024-03-01       B        196     82    327
6  2024-04-01       A        181    129    496
7  2024-04-01       B        163     73    359
8  2024-05-01       A        163     76    421
9  2024-05-01       B        118    131    513
10 2024-06-01       A        141    124    392
11 2024-06-01       B        111    138    404

In [12]:
fig = px.line(
    monthly_sales_pro,
    x="month",
    y="sales",
    markers=True,
    title="Monthly Total Sales by Product",
    color='product'
)

fig.update_layout(
    
    xaxis_title="Month",
    yaxis_title="Sales"
)

fig.show()

In [6]:
region_sales = (
    df_plotly.groupby("region", as_index=False)["sales"]
             .sum()
)

region_sales

  region  sales
0   East   1559
1  North   1800
2  South   1674

In [8]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    text="sales",
    title="Total Sales by Region"
)

fig.update_traces(textposition="outside")
fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales"
)

fig.show()

In [13]:
fig = px.scatter(
    df_plotly,
    x="customers",
    y="sales",
    color="region",
    hover_data=["product", "month_name", "units"],
    title="Customers vs Sales"
)

fig.update_layout(
    xaxis_title="Customers",
    yaxis_title="Sales",
    legend_title="Region"
)

fig.show()

In [14]:
monthly_region_sales = (
    df_plotly.groupby(["month", "region"], as_index=False)["sales"]
             .sum()
)

monthly_region_sales.head()

       month region  sales
0 2024-01-01   East    217
1 2024-01-01  North    276
2 2024-01-01  South    314
3 2024-02-01   East    273
4 2024-02-01  North    305

In [15]:
fig = px.line(
    monthly_region_sales,
    x="month",
    y="sales",
    color="region",
    markers=True,
    title="Monthly Sales by Region"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales",
    legend_title="Region"
)

fig.show()

In [16]:
region_product_sales = (
    df_plotly.groupby(["region", "product"], as_index=False)["sales"]
             .sum()
)

region_product_sales

  region product  sales
0   East       A    853
1   East       B    706
2  North       A    888
3  North       B    912
4  South       A    958
5  South       B    716

In [17]:
fig = px.bar(
    region_product_sales,
    x="region",
    y="sales",
    color="product",
    barmode="group",
    title="Sales by Region and Product"
)

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales",
    legend_title="Product"
)

fig.show()

In [18]:
product_sales = (
    df_plotly.groupby("product", as_index=False)["sales"]
             .sum()
)

product_sales

  product  sales
0       A   2699
1       B   2334

In [19]:
fig = px.pie(
    product_sales,
    names="product",
    values="sales",
    hole=0.5,
    title="Share of Total Sales by Product"
)

fig.update_traces(textinfo="label+percent")

fig.show()

Changing Colors in Plotly

Highlighting Only the Specific Categories

Vertical and Horizontal Reference Lines