Installings

In [5]:
#conda install plotly

In [6]:
#conda install nbformat

In [7]:
#import sys
#print(sys.executable)

Dummy Dataset for Plotly Examples

In [8]:
import pandas as pd
import numpy as np
import plotly.express as px

np.random.seed(42)
px.defaults.template = "plotly_white"

months = pd.date_range("2024-01-01", periods=6, freq="MS")
regions = ["North", "South", "East"]
products = ["A", "B"]

rows = []

for month in months:
    for region in regions:
        for product in products:
            sales = np.random.randint(80, 220)
            customers = np.random.randint(20, 90)
            units = np.random.randint(10, 70)
            
            rows.append([month, region, product, sales, customers, units])

df_plotly = pd.DataFrame(
    rows,
    columns=["month", "region", "product", "sales", "customers", "units"]
)

df_plotly["month_name"] = df_plotly["month"].dt.strftime("%b")
df_plotly.head()

       month region product  sales  customers  units month_name
0 2024-01-01  North       A    182         71     38        Jan
1 2024-01-01  North       B     94         80     30        Jan
2 2024-01-01  South       A    182         43     12        Jan
3 2024-01-01  South       B    132         21     33        Jan
4 2024-01-01   East       A    117         21     69        Jan

In [9]:
px.defaults.template = "plotly_white"

In [10]:
monthly_sales = df_plotly.groupby("month", as_index=False)[['customers', 'units', 'sales']].sum()
monthly_sales

       month  customers  units  sales
0 2024-01-01        288    203    807
1 2024-02-01        347    289    810
2 2024-03-01        380    151    831
3 2024-04-01        344    202    855
4 2024-05-01        281    207    934
5 2024-06-01        252    262    796

In [11]:
fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    #markers=True,
    title="Monthly Total Sales"
)

fig.update_layout(
    
    xaxis_title="Month",
    yaxis_title="Sales"
)

fig.show()

In [12]:
monthly_sales_pro = df_plotly.groupby(["month", "product"], as_index=False)[['customers', 'units', 'sales']].sum()
monthly_sales_pro

        month product  customers  units  sales
0  2024-01-01       A        135    119    481
1  2024-01-01       B        153     84    326
2  2024-02-01       A        176    151    405
3  2024-02-01       B        171    138    405
4  2024-03-01       A        184     69    504
5  2024-03-01       B        196     82    327
6  2024-04-01       A        181    129    496
7  2024-04-01       B        163     73    359
8  2024-05-01       A        163     76    421
9  2024-05-01       B        118    131    513
10 2024-06-01       A        141    124    392
11 2024-06-01       B        111    138    404

In [13]:
fig = px.line(
    monthly_sales_pro,
    x="month",
    y="sales",
    markers=True,
    title="Monthly Total Sales by Product",
    color='product'
)

fig.update_layout(
    
    xaxis_title="Month",
    yaxis_title="Sales"
)

fig.show()

In [14]:
region_sales = (
    df_plotly.groupby("region", as_index=False)["sales"]
             .sum()
)

region_sales

  region  sales
0   East   1559
1  North   1800
2  South   1674

In [15]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    text="sales",
    title="Total Sales by Region"
)

fig.update_traces(textposition="outside")
fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales"
)

fig.show()

In [16]:
fig = px.scatter(
    df_plotly,
    x="customers",
    y="sales",
    color="region",
    hover_data=["product", "month_name", "units"],
    title="Customers vs Sales"
)

fig.update_layout(
    xaxis_title="Customers",
    yaxis_title="Sales",
    legend_title="Region"
)

fig.show()

In [17]:
monthly_region_sales = (
    df_plotly.groupby(["month", "region"], as_index=False)["sales"]
             .sum()
)

monthly_region_sales.head()

       month region  sales
0 2024-01-01   East    217
1 2024-01-01  North    276
2 2024-01-01  South    314
3 2024-02-01   East    273
4 2024-02-01  North    305

In [18]:
fig = px.line(
    monthly_region_sales,
    x="month",
    y="sales",
    color="region",
    markers=True,
    title="Monthly Sales by Region"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales",
    legend_title="Region"
)

fig.show()

In [19]:
region_product_sales = (
    df_plotly.groupby(["region", "product"], as_index=False)["sales"]
             .sum()
)

region_product_sales

  region product  sales
0   East       A    853
1   East       B    706
2  North       A    888
3  North       B    912
4  South       A    958
5  South       B    716

In [20]:
fig = px.bar(
    region_product_sales,
    x="region",
    y="sales",
    color="product",
    barmode="group",
    title="Sales by Region and Product"
)

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales",
    legend_title="Product"
)

fig.show()

In [21]:
product_sales = (
    df_plotly.groupby("product", as_index=False)["sales"]
             .sum()
)

product_sales

  product  sales
0       A   2699
1       B   2334

In [22]:
fig = px.pie(
    product_sales,
    names="product",
    values="sales",
    hole=0.5,
    title="Share of Total Sales by Product"
)

fig.update_traces(textinfo="label+percent")

fig.show()

Changing Colors in Plotly

In [23]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    title="Total Sales by Region",
    color_discrete_sequence=["#c543a9"]
)

fig.show()

In [24]:
fig = px.bar(
    region_product_sales,
    x="region",
    y="sales",
    color="product",
    barmode="group",
    title="Sales by Region and Product",
    color_discrete_sequence=["#3B6EAD", "#AFC4E8"]
)

fig.show()

In [25]:
fig = px.bar(
    region_product_sales,
    x="region",
    y="sales",
    color="product",
    barmode="group",
    title="Sales by Region and Product",
    color_discrete_map={
        "A": "#3B6EAD",
        "B": "#AFC4E8"
    }
)

fig.show()

In [26]:
fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    markers=True,
    title="Monthly Total Sales",
    color_discrete_sequence=["crimson"]
)

fig.show()

In [27]:
fig = px.line(
    monthly_region_sales,
    x="month",
    y="sales",
    color="region",
    markers=True,
    title="Monthly Sales by Region",
    color_discrete_sequence=["#1f77b4", "#ff7f0e", "#2ca02c"]
)

fig.show()

In [28]:
fig = px.histogram(
    df_plotly,
    x="sales",
    nbins=15,
    title="Distribution of Sales",
    color_discrete_sequence=["purple"]
)

fig.show()

In [29]:
fig = px.scatter(
    df_plotly,
    x="customers",
    y="sales",
    title="Customers vs Sales",
    color_discrete_sequence=["darkorange"]
)

fig.show()

In [30]:
fig = px.scatter(
    df_plotly,
    x="customers",
    y="sales",
    color="region",
    title="Customers vs Sales by Region",
    color_discrete_sequence=["#3B6EAD", "#AFC4E8", "#B7C2D1"]
)

fig.show()

In [31]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    title="Total Sales by Region"
)

fig.update_traces(marker_color="teal")

fig.show()

In [32]:
fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    title="Monthly Total Sales"
)

fig.update_traces(line_color="red")

fig.show()

Highlighting Only the Specific Categories

In [ ]:
region_sales

pd.concat([region_sales,{'region' : top_region}] axis=1)

  region  sales
0   East   1559
1  North   1800
2  South   1674

In [38]:
max_number = region_sales['sales'].max()
max_number

np.int64(1800)

In [42]:
top_region = region_sales.loc[region_sales['sales'].idxmax(), ['region']]
top_region

region    North
Name: 1, dtype: str

In [60]:
region_sales = (
    df_plotly.groupby("region", as_index=False)["sales"]
             .sum()
)

top_region = region_sales.loc[region_sales["sales"].idxmax(), "region"]

region_sales["highlight"] = np.where(
    region_sales["region"] == top_region,
    "Highest Sales",
    "Other Regions"
)

region_sales

  region  sales      highlight
0   East   1559  Other Regions
1  North   1800  Highest Sales
2  South   1674  Other Regions

In [64]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    color="highlight",
    text="sales",
    title="Highlighting Only the Largest Category",
    color_discrete_map={
        "Highest Sales": "#3B6EAD",
        "Other Regions": "#D9D9D9"
    }
)

fig.update_traces(textposition="outside")

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales",
    legend_title=""
)

fig.show()

Personalized bar chart - initial version - correction in templates.py

In [63]:
def my_bar_plot(df:pd.DataFrame, x_col:str, y_col:float, flag:bool =True)-> px.bar:
    
    df_agg = (
    df.groupby(x_col, as_index=False)[y_col]
             .sum()
    )   

    if flag:
        flag_region = df_agg.loc[df_agg[x_col].idxmax(), y_col]
        df_agg["highlight"] = np.where(
            df_agg[y_col] == flag_region,
            f"Highest {y_col.capitalize()}",
            f"Other {x_col.capitalize()}"
        )
        colorizer = {
            f"Highest {y_col.capitalize()}": "#3B6EAD",
            f"Other {x_col.capitalize()}": "#D9D9D9"
        }
    else:
        flag_region = df_agg.loc[df_agg[x_col].idxmin(), y_col]
        df_agg["highlight"] = np.where(
            df_agg[y_col] == flag_region,
            f"Lowest {y_col.capitalize()}",
            f"Other {x_col.capitalize()}"
        )
        colorizer = {
            f"Lowest {y_col.capitalize()}": "#3B6EAD",
            f"Other {x_col.capitalize()}": "#D9D9D9"
        }
        

    fig = px.bar(
    df_agg,
    x=x_col,
    y=y_col,
    color="highlight",

    title=f'Total {y_col.capitalize()} by {x_col.capitalize()}',
    color_discrete_map=colorizer
    )

    fig.update_traces(textposition="outside")
    

    fig.update_layout(
        xaxis_title=x_col.capitalize(),
        yaxis_title=y_col.capitalize(),
        legend_title="",
        
        
        
    )

        
    
    return fig

Vertical and Horizontal Reference Lines