In [5]:
import numpy as np
import pandas as pd

In [6]:
rng = np.random.default_rng(42)

df_sampling = pd.DataFrame(
    {
        "user_id": np.arange(1, 101),
        "category": rng.choice(["A", "B", "C"], size=100, p=[0.5, 0.3, 0.2]),
        "score": rng.normal(loc=75, scale=10, size=100).round(2),
    }
)

In [8]:
rng.choice(["A", "B", "C"])

np.str_('B')

In [9]:
df_sampling.head()

   user_id category  score
0        1        B  79.00
1        2        A  65.95
2        3        C  71.22
3        4        B  87.99
4        5        A  71.44

In [10]:
df_sampling.shape

(100, 3)

In [11]:
df_sampling['score'].describe()[['mean', 'std']]

mean    74.859800
std      9.843752
Name: score, dtype: float64

In [12]:
df_sampling['category'].value_counts()

category
A    53
B    33
C    14
Name: count, dtype: int64

In [13]:
df_sampling['category'].value_counts(normalize=True)

category
A    0.53
B    0.33
C    0.14
Name: proportion, dtype: float64

Random Sampling

In [14]:
rs = df_sampling.sample(n = 30, random_state=42)

In [16]:
rs['score'].describe()[['mean', 'std']]

mean    72.739667
std      8.956177
Name: score, dtype: float64

In [17]:
rs.head()

    user_id category  score
83       84        A  77.19
53       54        B  64.64
70       71        A  73.43
45       46        C  77.68
44       45        C  53.68

In [19]:
rs.groupby('category')['score'].describe()[['mean', 'std', 'count']]

               mean        std  count
category
A         73.318000  10.134300   15.0
B         74.975556   6.108523    9.0
C         67.940000   8.961924    6.0

In [20]:
rs['category'].value_counts(normalize=True)

category
A    0.5
B    0.3
C    0.2
Name: proportion, dtype: float64

1:23:30
Stratified Sampling

In [22]:
stratified_sampling = (df_sampling
                    .groupby('category', group_keys=False)
                    .sample(frac=0.2, random_state=42))

stratified_sampling.head()

    user_id category  score
38       39        A  78.14
83       84        A  77.19
92       93        A  92.24
28       29        A  89.63
85       86        A  86.06

In [23]:
(stratified_sampling
.groupby('category')['score']
.describe()[['mean', 'std', 'count']])

               mean        std  count
category
A         76.688182  10.510287   11.0
B         78.715714  10.081969    7.0
C         63.650000   5.447054    3.0

In [24]:
(df_sampling
.groupby('category')['score']
.describe()[['mean', 'std', 'count']])

               mean        std  count
category
A         74.200000   8.973076   53.0
B         76.272424  10.014058   33.0
C         74.027857  12.705514   14.0