In [1]:
import pandas as pd
from scipy import stats
import plotly.express as px

In [3]:
df = pd.read_csv('../data/ab_testing/fast_food.csv')
df.head()

,MarketID,MarketSize,LocationID,AgeOfStore,Promotion,week,SalesInThousands
0,1,Medium,1,4,3,1,33.73
1,1,Medium,1,4,3,2,35.67
2,1,Medium,1,4,3,3,29.03
3,1,Medium,1,4,3,4,39.25
4,1,Medium,2,5,2,1,27.81

In [4]:
df.describe()

,MarketID,LocationID,AgeOfStore,Promotion,week,SalesInThousands
count,548.000000,548.000000,548.000000,548.000000,548.000000,548.000000
mean,5.715328,479.656934,8.503650,2.029197,2.500000,53.466204
std,2.877001,287.973679,6.638345,0.810729,1.119055,16.755216
min,1.000000,1.000000,1.000000,1.000000,1.000000,17.340000
25%,3.000000,216.000000,4.000000,1.000000,1.750000,42.545000
50%,6.000000,504.000000,7.000000,2.000000,2.500000,50.200000
75%,8.000000,708.000000,12.000000,3.000000,3.250000,60.477500
max,10.000000,920.000000,28.000000,3.000000,4.000000,99.650000

In [5]:
df['MarketID'].value_counts()

MarketID
3     88
10    80
5     60
6     60
7     60
1     52
8     48
9     40
4     36
2     24
Name: count, dtype: int64

In [6]:
df['MarketSize'].value_counts()

MarketSize
Medium    320
Large     168
Small      60
Name: count, dtype: int64

In [8]:
fig = px.box(
    df,
    x = "Promotion",
    y = "SalesInThousands",
    color = "Promotion",
    title = "Sales Distribution by Promotion"
)

fig

In [14]:
weekly_sales = (
    df.groupby(["week","Promotion"])['SalesInThousands'].mean().reset_index()
)

In [15]:
weekly_sales.head()

   week  Promotion  SalesInThousands
0     1          1         58.244419
1     1          2         47.730213
2     1          3         55.776170
3     2          1         56.929535
4     2          2         47.582553

In [17]:
px.line(
    data_frame = weekly_sales,
    x = "week",
    y = "SalesInThousands",
    color = "Promotion"

)

In [20]:
px.box(
    data_frame = df,
    x = 'MarketSize',
    y = 'SalesInThousands',
    color = "Promotion",
    title = "Sales By MarketSize per Promotion"
)

In [21]:
fig = px.scatter(
    df,
    x="AgeOfStore",
    y="SalesInThousands",
    color="Promotion",
    trendline="ols",
    title="Sales vs Store Age"
)
fig.show()